collections:
  tutorials:
    output: true
    order:
      - page1.md
      - page2.md
      - page3.md
      - page4.md
      - page5.md
      - page6.md
      - page7.md
      - page8.md
      - page9.md
      - page10.md
  docs_v1:
    output: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
